# False positives - these are actual package names, not secrets
# Test files contain fake API keys for security scanner testing
paths-ignore:
  - 'packages/*.txt'
  - 'packages/*.json'
  - '**/test-*.js'
  - '**/test-*.py'
  - '**/test_*.py'
  - '**/test-files/**'
  - '**/tests/**'
  - 'SETUP.md'
  - '**/vuln-demo.*'
